ignore:
  - "cmd/escalier/main.go"
  - "cmd/lsp-server/*.go"
  - "internal/codegen/ast.go"
  - "internal/parser/token.go"
  - "internal/provenance/**"
  - "internal/type_system/**"
  - "tools/**"
  - "wasm_exec.js"
  - "**/examples/**"
  - "**/fixtures/**"
