package dts_to_esc

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/escalier-lang/escalier/internal/set"
	"github.com/gkampitakis/go-snaps/snaps"
	"github.com/stretchr/testify/require"
)

// seedLibDir writes one synthetic `lib.*.d.ts` into a fresh directory
// and returns that directory.
func seedLibDir(t *testing.T, contents string) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "lib.es5.d.ts"), []byte(contents), 0o644))
	return dir
}

// runGenerate runs one generation over generateLib with the given
// overlay files, and returns the output root.
func runGenerate(t *testing.T, overlay map[string]string) (string, *GenerateResult) {
	t.Helper()
	outDir := t.TempDir()
	res, err := Generate(GenerateOptions{
		LibDir:     seedLibDir(t, overlayLib),
		OverlayDir: seedOverlay(t, overlay),
		OutDir:     outDir,
	})
	require.NoError(t, err)
	return outDir, res
}

// readPackage returns the contents of one generated package file.
func readPackage(t *testing.T, outDir, file string) string {
	t.Helper()
	contents, err := os.ReadFile(filepath.Join(outDir, filepath.FromSlash(file)))
	require.NoError(t, err)
	return string(contents)
}

// treeUnder returns every file under root, as sorted slash paths
// relative to it.
func treeUnder(t *testing.T, root string) []string {
	t.Helper()
	var out []string
	require.NoError(t, filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		out = append(out, filepath.ToSlash(rel))
		return nil
	}))
	sort.Strings(out)
	return out
}

// TestGenerate_WritesTheTreeWithAHeader pins what a run with an empty
// overlay lays down. Every package file opens with the banner naming the
// command that rewrites it, which is how a reader tells a generated file
// from a hand-authored one without re-running the generator.
func TestGenerate_WritesTheTreeWithAHeader(t *testing.T) {
	t.Parallel()
	outDir, res := runGenerate(t, nil)

	require.Equal(t, []string{"std:array", "std:number"}, res.Written)
	require.Empty(t, res.Removed)
	require.Equal(t, []string{
		"node/README.md", "std/array.esc", "std/number.esc",
	}, treeUnder(t, outDir))

	snaps.MatchInlineSnapshot(t, readPackage(t, outDir, "std/array.esc"), snaps.Inline(`// Code generated by `+"`"+`dts_to_esc generate`+"`"+`. DO NOT EDIT.
// Inputs: the pinned lib.*.d.ts set, internal/ecma262, and
// internal/interop/overlay/. Change one of those and re-run.

@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}

export declare interface ArrayLike<T> {
    readonly length: number
}
`))
}

// TestGenerate_IsIdempotent is the §6.6 gate: the run reads no file it
// wrote, so a second one over the same inputs leaves the tree
// byte-identical and `git diff` stays the review surface for a version
// bump.
func TestGenerate_IsIdempotent(t *testing.T) {
	t.Parallel()
	libDir := seedLibDir(t, overlayLib)
	overlayDir := seedOverlay(t, map[string]string{
		"std/array.replace.esc": "export declare class Array<T> {\n" +
			"    at(mut self, index: number) -> T,\n}\n",
		"std/array.add.esc": "export declare interface ArrayLike<T> {\n" +
			"    readonly first: T,\n}\n",
	})
	outDir := t.TempDir()
	opts := GenerateOptions{LibDir: libDir, OverlayDir: overlayDir, OutDir: outDir}

	_, err := Generate(opts)
	require.NoError(t, err)
	first := readPackage(t, outDir, "std/array.esc")

	_, err = Generate(opts)
	require.NoError(t, err)
	require.Equal(t, first, readPackage(t, outDir, "std/array.esc"))
}

// TestGenerate_RemovesAPackageNoInputAccountsFor covers stale-output
// removal. A package that stops being routed leaves the tree rather than
// lingering as a file no input produces, and so does a file that matches
// no package at all.
func TestGenerate_RemovesAPackageNoInputAccountsFor(t *testing.T) {
	t.Parallel()
	outDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(outDir, "std"), 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(outDir, "std", "date.esc"), []byte("// stale\n"), 0o644))
	require.NoError(t, os.WriteFile(
		filepath.Join(outDir, "std", "nonesuch.esc"), []byte("// orphan\n"), 0o644))

	res, err := Generate(GenerateOptions{
		LibDir:     seedLibDir(t, overlayLib),
		OverlayDir: seedOverlay(t, nil),
		OutDir:     outDir,
	})
	require.NoError(t, err)
	require.Equal(t, []string{"std/date.esc", "std/nonesuch.esc"}, res.Removed)
	require.Equal(t, []string{
		"node/README.md", "std/array.esc", "std/number.esc",
	}, treeUnder(t, outDir))
}

// TestGenerate_LeavesAHandAuthoredPackageAlone covers the exemption. A
// package with no upstream counterpart is committed like any other
// source file, so the run neither writes it nor deletes it.
func TestGenerate_LeavesAHandAuthoredPackageAlone(t *testing.T) {
	t.Parallel()
	outDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(outDir, "std"), 0o755))
	const handAuthored = "@js(\"Math.PI\")\nexport val PI: number = 3.14\n"
	require.NoError(t, os.WriteFile(
		filepath.Join(outDir, "std", "math.esc"), []byte(handAuthored), 0o644))

	res, err := Generate(GenerateOptions{
		LibDir:       seedLibDir(t, overlayLib),
		OverlayDir:   seedOverlay(t, nil),
		OutDir:       outDir,
		HandAuthored: set.FromSlice([]string{"std:math"}),
	})
	require.NoError(t, err)
	require.Empty(t, res.Removed)
	require.Equal(t, handAuthored, readPackage(t, outDir, "std/math.esc"))
}
