package dts_to_esc

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/escalier-lang/escalier/internal/set"
	"github.com/gkampitakis/go-snaps/snaps"
	"github.com/stretchr/testify/require"
)

// generateLib is the synthetic `.d.ts` input the generate tests route.
// It holds one trio, which converts to `class Array`, one plain
// interface, which stays an interface, and one free function, so the
// overlay's member operations are exercised against each shape and the
// run emits two packages rather than one.
const generateLib = `
interface Array<T> { length: number; at(index: number): T | undefined; }
interface ArrayConstructor { new <T>(): Array<T>; isArray(arg: any): boolean; }
declare var Array: ArrayConstructor;
interface ArrayLike<T> { readonly length: number; }
declare function parseInt(string: string, radix?: number): number;
`

// seedLibDir writes one synthetic `lib.*.d.ts` into a fresh directory
// and returns that directory.
func seedLibDir(t *testing.T, contents string) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "lib.es5.d.ts"), []byte(contents), 0o644))
	return dir
}

// runGenerate runs one generation over generateLib with the given
// overlay files, and returns the output root.
func runGenerate(t *testing.T, overlay map[string]string) (string, *GenerateResult) {
	t.Helper()
	outDir := t.TempDir()
	res, err := Generate(GenerateOptions{
		LibDir:     seedLibDir(t, generateLib),
		OverlayDir: seedOverlay(t, overlay),
		OutDir:     outDir,
	})
	require.NoError(t, err)
	return outDir, res
}

// generateError runs one generation expected to fail and returns the
// message.
func generateError(t *testing.T, overlay map[string]string) string {
	t.Helper()
	_, err := Generate(GenerateOptions{
		LibDir:     seedLibDir(t, generateLib),
		OverlayDir: seedOverlay(t, overlay),
		OutDir:     t.TempDir(),
	})
	require.Error(t, err)
	return err.Error()
}

// readPackage returns the contents of one generated package file.
func readPackage(t *testing.T, outDir, file string) string {
	t.Helper()
	contents, err := os.ReadFile(filepath.Join(outDir, filepath.FromSlash(file)))
	require.NoError(t, err)
	return string(contents)
}

// treeUnder returns every file under root, as sorted slash paths
// relative to it.
func treeUnder(t *testing.T, root string) []string {
	t.Helper()
	var out []string
	require.NoError(t, filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		out = append(out, filepath.ToSlash(rel))
		return nil
	}))
	sort.Strings(out)
	return out
}

// TestGenerate_WritesTheTreeWithAHeader pins what a run with an empty
// overlay lays down. Every package file opens with the banner naming the
// command that rewrites it, which is how a reader tells a generated file
// from a hand-authored one without re-running the generator.
func TestGenerate_WritesTheTreeWithAHeader(t *testing.T) {
	t.Parallel()
	outDir, res := runGenerate(t, nil)

	require.Equal(t, []string{"std:array", "std:number"}, res.Written)
	require.Empty(t, res.Removed)
	require.Equal(t, []string{
		"node/README.md", "std/array.esc", "std/number.esc",
	}, treeUnder(t, outDir))

	snaps.MatchInlineSnapshot(t, readPackage(t, outDir, "std/array.esc"), snaps.Inline(`// Code generated by `+"`"+`dts_to_esc generate`+"`"+`. DO NOT EDIT.
// Inputs: the pinned lib.*.d.ts set, internal/ecma262, and
// internal/interop/overlay/. Change one of those and re-run.

@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}

export declare interface ArrayLike<T> {
    readonly length: number
}
`))
}

// TestGenerate_IsIdempotent is the §6.6 gate: the run reads no file it
// wrote, so a second one over the same inputs leaves the tree
// byte-identical and `git diff` stays the review surface for a version
// bump.
func TestGenerate_IsIdempotent(t *testing.T) {
	t.Parallel()
	libDir := seedLibDir(t, generateLib)
	overlayDir := seedOverlay(t, map[string]string{
		"std/array.replace.esc": "export declare class Array<T> {\n" +
			"    at(mut self, index: number) -> T,\n}\n",
		"std/array.add.esc": "export declare interface ArrayLike<T> {\n" +
			"    readonly first: T,\n}\n",
	})
	outDir := t.TempDir()
	opts := GenerateOptions{LibDir: libDir, OverlayDir: overlayDir, OutDir: outDir}

	_, err := Generate(opts)
	require.NoError(t, err)
	first := readPackage(t, outDir, "std/array.esc")

	_, err = Generate(opts)
	require.NoError(t, err)
	require.Equal(t, first, readPackage(t, outDir, "std/array.esc"))
}

// TestGenerate_OverlayOperations covers what each operation does to the
// converted package. The `replace` cases also pin substitution in place
// rather than append, which is what keeps a second run byte-identical.
func TestGenerate_OverlayOperations(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		overlay map[string]string
		want    string
	}{
		{
			name: "add reaches a converted class",
			overlay: map[string]string{
				"std/array.add.esc": "export declare class Array<T> {\n" +
					"    static of<T>(...items: Array<T>) -> Array<T>,\n}\n",
			},
			want: `@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined,
    constructor(mut self),
    static isArray(arg: any) -> boolean,
    static of<T>(...items: Array<T>) -> Array<T>
}

export declare interface ArrayLike<T> {
    readonly length: number
}
`,
		},
		{
			name: "add reaches a converted interface",
			overlay: map[string]string{
				"std/array.add.esc": "export declare interface ArrayLike<T> {\n" +
					"    readonly first: T,\n}\n",
			},
			want: `@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}

export declare interface ArrayLike<T> {
    readonly length: number,
    readonly first: T
}
`,
		},
		{
			name: "add contributes a declaration no upstream source has",
			overlay: map[string]string{
				"std/array.add.esc": "@js(\"Symbol.iterator\")\n" +
					"export declare val iteratorKey: unique symbol\n",
			},
			want: `@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}

export declare interface ArrayLike<T> {
    readonly length: number
}

@js("Symbol.iterator")
export declare val iteratorKey: unique symbol
`,
		},
		{
			name: "replace substitutes a member at its own position",
			overlay: map[string]string{
				"std/array.replace.esc": "export declare class Array<T> {\n" +
					"    at(self, index: number) -> T,\n}\n",
			},
			want: `@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}

export declare interface ArrayLike<T> {
    readonly length: number
}
`,
		},
		{
			name: "replace stands in for a whole declaration of another kind",
			overlay: map[string]string{
				"std/array.replace.esc": "export declare type ArrayLike<T> = { length: number }\n",
			},
			want: `@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}

export declare type ArrayLike<T> = {
    length: number
}
`,
		},
		{
			name: "drop keeps a member out of the output",
			overlay: map[string]string{
				"std/array.drop.esc": "export declare interface Array {\n" +
					"    at: unknown,\n}\n",
			},
			want: `@js("Array")
export declare class Array<T> {
    length: number,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}

export declare interface ArrayLike<T> {
    readonly length: number
}
`,
		},
		{
			name: "drop keeps a whole declaration out of the output",
			overlay: map[string]string{
				"std/array.drop.esc": "export declare val ArrayLike\n",
			},
			want: `@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined,
    constructor(mut self),
    static isArray(arg: any) -> boolean
}
`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			outDir, _ := runGenerate(t, tt.overlay)
			require.Equal(t, GeneratedHeader+tt.want, readPackage(t, outDir, "std/array.esc"))
		})
	}
}

// TestGenerate_RootDropKeepsASymbolOutOfEveryPackage covers the one
// operation that resolves during routing rather than against a
// converted module.
func TestGenerate_RootDropKeepsASymbolOutOfEveryPackage(t *testing.T) {
	t.Parallel()
	outDir, res := runGenerate(t, map[string]string{
		"drop.esc": "export declare val parseInt\n",
	})
	require.Equal(t, []string{"std:array"}, res.Written)
	require.Equal(t, []string{"node/README.md", "std/array.esc"}, treeUnder(t, outDir))
}

// TestGenerate_RejectsAnOverlayTheUpstreamSourceNoLongerBacks is the
// TypeScript-side-removal signal. The run overwrites the tree without
// reading it, so a stale overlay entry is the only place a removal can
// be caught.
func TestGenerate_RejectsAnOverlayTheUpstreamSourceNoLongerBacks(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		overlay map[string]string
		want    string
	}{
		{
			name:    "root drop naming a symbol no lib file declares",
			overlay: map[string]string{"drop.esc": "export declare val eval\n"},
			want:    "overlay: drop.esc drops eval, which no lib.*.d.ts file declares",
		},
		{
			name: "drop naming an absent declaration",
			overlay: map[string]string{
				"std/array.drop.esc": "export declare val ReadonlyArray\n",
			},
			want: "overlay: std/array.drop.esc drops ReadonlyArray, which std:array does not declare",
		},
		{
			name: "drop naming an absent member",
			overlay: map[string]string{
				"std/array.drop.esc": "export declare interface Array {\n    sort: unknown,\n}\n",
			},
			want: "overlay: std/array.drop.esc drops Array.sort, which the converted " +
				"declaration does not have",
		},
		{
			name: "replace naming an absent declaration",
			overlay: map[string]string{
				"std/array.replace.esc": "export declare val ReadonlyArray\n",
			},
			want: "overlay: std/array.replace.esc replaces ReadonlyArray, which std:array does not declare",
		},
		{
			name: "replace naming an absent member",
			overlay: map[string]string{
				"std/array.replace.esc": "export declare class Array<T> {\n" +
					"    sort(mut self) -> Self,\n}\n",
			},
			want: "overlay: std/array.replace.esc replaces Array.sort, which the converted " +
				"declaration does not have",
		},
		{
			name: "add colliding with a converted member",
			overlay: map[string]string{
				"std/array.add.esc": "export declare class Array<T> {\n" +
					"    at(mut self, index: number) -> T,\n}\n",
			},
			want: "overlay: std/array.add.esc adds Array.at, which the converted declaration " +
				"already has; correct it with a replace overlay instead",
		},
		{
			name: "add colliding with a converted declaration",
			overlay: map[string]string{
				"std/array.add.esc": "export declare val ArrayLike\n",
			},
			want: "overlay: std/array.add.esc adds the interface ArrayLike, which std:array " +
				"already declares; correct an existing declaration with a replace overlay",
		},
		{
			name: "replace on a package nothing routes to",
			overlay: map[string]string{
				"std/date.replace.esc": "export declare val Date\n",
			},
			want: "overlay: std/date.replace.esc replaces in std:date, which no upstream " +
				"declaration routes to",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, generateError(t, tt.overlay))
		})
	}
}

// TestGenerate_AddCreatesAPackageNothingRoutesTo keeps an addition from
// being silently lost when no upstream declaration lands in the package
// it names.
func TestGenerate_AddCreatesAPackageNothingRoutesTo(t *testing.T) {
	t.Parallel()
	outDir, res := runGenerate(t, map[string]string{
		"std/date.add.esc": "@js(\"Date.now\")\nexport declare fn now() -> number\n",
	})
	require.Equal(t, []string{"std:array", "std:date", "std:number"}, res.Written)
	require.Equal(t, GeneratedHeader+`@js("Date.now")
export declare fn now() -> number
`, readPackage(t, outDir, "std/date.esc"))
}

// TestGenerate_RemovesAPackageNoInputAccountsFor covers stale-output
// removal. A package that stops being routed leaves the tree rather than
// lingering as a file no input produces, and so does a file that matches
// no package at all.
func TestGenerate_RemovesAPackageNoInputAccountsFor(t *testing.T) {
	t.Parallel()
	outDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(outDir, "std"), 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(outDir, "std", "date.esc"), []byte("// stale\n"), 0o644))
	require.NoError(t, os.WriteFile(
		filepath.Join(outDir, "std", "nonesuch.esc"), []byte("// orphan\n"), 0o644))

	res, err := Generate(GenerateOptions{
		LibDir:     seedLibDir(t, generateLib),
		OverlayDir: seedOverlay(t, nil),
		OutDir:     outDir,
	})
	require.NoError(t, err)
	require.Equal(t, []string{"std/date.esc", "std/nonesuch.esc"}, res.Removed)
	require.Equal(t, []string{
		"node/README.md", "std/array.esc", "std/number.esc",
	}, treeUnder(t, outDir))
}

// TestGenerate_LeavesAHandAuthoredPackageAlone covers the exemption. A
// package with no upstream counterpart is committed like any other
// source file, so the run neither writes it nor deletes it.
func TestGenerate_LeavesAHandAuthoredPackageAlone(t *testing.T) {
	t.Parallel()
	outDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(outDir, "std"), 0o755))
	const handAuthored = "@js(\"Math.PI\")\nexport val PI: number = 3.14\n"
	require.NoError(t, os.WriteFile(
		filepath.Join(outDir, "std", "math.esc"), []byte(handAuthored), 0o644))

	res, err := Generate(GenerateOptions{
		LibDir:       seedLibDir(t, generateLib),
		OverlayDir:   seedOverlay(t, nil),
		OutDir:       outDir,
		HandAuthored: set.FromSlice([]string{"std:math"}),
	})
	require.NoError(t, err)
	require.Empty(t, res.Removed)
	require.Equal(t, handAuthored, readPackage(t, outDir, "std/math.esc"))
}
