package dts_to_esc

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/escalier-lang/escalier/internal/ast"
	"github.com/escalier-lang/escalier/internal/dts_parser"
	"github.com/escalier-lang/escalier/internal/set"
	"github.com/tidwall/btree"
)

// GeneratedHeader opens every `.esc` file a run writes. Two kinds of
// file live under internal/interop/data/, generated packages and
// hand-authored ones, and a reader has to tell them apart without
// re-running the generator and diffing the result. The header marks the
// file as a build output and names the command that rewrites it.
//
// The first line follows Go's `// Code generated ... DO NOT EDIT.`
// convention, which review tooling already recognizes.
//
// The banner names the three input layers rather than the directories
// they were read from, since `--overlay` moves one of them and the
// output would otherwise record where a particular run happened to read.
const GeneratedHeader = "// Code generated by `dts_to_esc generate`. DO NOT EDIT.\n" +
	"// Its facts come from the pinned lib.*.d.ts set, the ECMA-262\n" +
	"// derived facts, and the overlay. Change one of those and re-run.\n\n"

// LibInput is one `.d.ts` file fed to PartitionLib.
//
// SourceFile is the basename used for routing decisions (e.g.
// "lib.dom.d.ts" — see Route and DOMResidualSources). Module is the
// already-parsed dts module.
type LibInput struct {
	SourceFile string
	Module     *dts_parser.Module
}

// PartitionResult is the bucketed output of PartitionLib: top-level
// dts statements grouped by their target pseudo-package, plus the
// dropped-name notes the converter logs per §6.1.
//
// Buckets is keyed by package URI ("std:array", "web:dom", …) so
// callers can iterate in a stable order via PackageList. Within each
// bucket, statements are kept in the order they were routed (source-
// file order, then statement order within a file), then interface-
// and namespace-merged so trio detection sees one declaration per
// name.
type PartitionResult struct {
	Buckets map[string][]dts_parser.Statement

	// Drops records (name, source-file basename) pairs for every
	// top-level declaration the run skipped, whether the overlay's root
	// drop file named it or a DroppedSources file declared it. Callers
	// may surface these as informational warnings. They are intentional,
	// not errors.
	Drops []DropNote
}

// DropNote is one (name, source-file basename) pair in
// PartitionResult.Drops.
type DropNote struct {
	Name       string
	SourceFile string
}

// PartitionLib routes every top-level declaration across the inputs
// into its target package per Route, with no overlay. Returns an error
// on the first unmapped symbol (§6.1 fail-safe).
//
// With no overlay nothing is dropped by name, so the pinned lib set
// does not route through this entry point. Every name the committed
// root drop file holds would trip the fail-safe instead. This suits a
// synthetic input whose names all route. A file in DroppedSources
// still contributes nothing and still reaches Drops, which needs no
// overlay. Generate calls PartitionLibWithOverlay.
func PartitionLib(inputs []LibInput) (*PartitionResult, error) {
	return PartitionLibWithOverlay(inputs, nil)
}

// PartitionLibWithOverlay routes every top-level declaration across the
// inputs into its target package per Route, skipping the names the
// overlay's root drop file holds. A whole-symbol drop resolves here
// rather than in Route because it belongs to no package, so it has to
// be settled before the partition lookup assigns one.
//
// A drop naming a symbol the lib set does not declare fails the run.
// That is the TypeScript-side-removal signal for the overlay: the tree
// the run overwrites is never consulted, so the overlay is the only
// place a stale name can be caught.
//
// A file in DroppedSources contributes nothing. Every declaration in it
// is recorded in Drops, including the ones that augment a type another
// lib file owns.
//
// Inputs are processed in the order given so that interface-merge and
// namespace-merge results are stable. Routing keys off the input's
// SourceFile, not where a declaration physically lives in a nested
// namespace — top-level `declare namespace Intl { ... }` routes as a
// single unit to std:intl regardless of which lib file declared it.
func PartitionLibWithOverlay(inputs []LibInput, overlay *Overlay) (*PartitionResult, error) {
	out := &PartitionResult{
		Buckets: make(map[string][]dts_parser.Statement),
	}
	overlayDrops := overlay.GlobalDrops()
	matched := set.NewSet[string]()
	for _, in := range inputs {
		if in.Module == nil {
			return nil, fmt.Errorf("partition: nil module for %s", in.SourceFile)
		}
		dropped := DroppedSources.Contains(in.SourceFile)
		for _, stmt := range in.Module.Statements {
			name := topLevelName(stmt)
			if name == "" {
				// Statement carries no addressable top-level name
				// (ImportDecl, NamedExportStmt, ExportAllStmt, etc.).
				// The standalone converter already drops these for
				// MVP — keep parity here so PartitionLib doesn't push
				// unroutable statements into a bucket.
				continue
			}
			// A name declared in a DroppedSources file counts as
			// matched even though the file contributes nothing, so an
			// overlay drop of it is not reported as stale.
			overlayDropped := overlayDrops.Contains(name)
			if overlayDropped {
				matched.Add(name)
			}
			if dropped || overlayDropped {
				out.Drops = append(out.Drops,
					DropNote{Name: name, SourceFile: in.SourceFile})
				continue
			}
			res := Route(name, in.SourceFile)
			if res.Unmapped {
				return nil, UnmappedError(name, in.SourceFile)
			}
			out.Buckets[res.Pkg.URI] = append(out.Buckets[res.Pkg.URI], stmt)
		}
	}
	for _, name := range sortedNames(overlayDrops) {
		if !matched.Contains(name) {
			return nil, fmt.Errorf(
				"overlay: %s drops %s, which no lib.*.d.ts file declares",
				RootDropFile, name)
		}
	}
	for uri, stmts := range out.Buckets {
		out.Buckets[uri] = mergeDecls(stmts)
	}
	return out, nil
}

// topLevelName returns the addressable name of a top-level statement,
// or "" for statements that carry none (ImportDecl, re-export forms,
// ambient module/global blocks).
func topLevelName(stmt dts_parser.Statement) string {
	switch s := stmt.(type) {
	case *dts_parser.VarDecl:
		return s.Name.Name
	case *dts_parser.FuncDecl:
		return s.Name.Name
	case *dts_parser.ClassDecl:
		return s.Name.Name
	case *dts_parser.InterfaceDecl:
		return s.Name.Name
	case *dts_parser.TypeDecl:
		return s.Name.Name
	case *dts_parser.EnumDecl:
		return s.Name.Name
	case *dts_parser.NamespaceDecl:
		return s.Name.Name
	}
	return ""
}

// mergeDecls performs TS-style declaration merging within a routed
// bucket: same-named InterfaceDecl entries collapse into a single
// InterfaceDecl whose Members is the concatenation; same-named
// NamespaceDecl entries collapse into a single NamespaceDecl whose
// Statements is the concatenation (then recursively merged). The
// first occurrence's doc, span, and type-params are kept; later
// duplicates' metadata is dropped.
//
// This is how the converter handles the canonical TS-shipping pattern
// where the *same* interface is declared across multiple `lib.*.d.ts`
// files to layer in new spec revisions. For example, `interface
// Array<T>` is declared in:
//
//   - lib.es5.d.ts                  (push, pop, slice, map, filter, …)
//   - lib.es2015.core.d.ts          (find, findIndex, fill, copyWithin, …)
//   - lib.es2015.iterable.d.ts      (entries, keys, values, [Symbol.iterator])
//   - lib.es2015.symbol.wellknown.d.ts ([Symbol.unscopables])
//   - lib.es2016.array.include.d.ts (includes)
//   - lib.es2022.array.d.ts         (at)
//   - lib.es2023.array.d.ts         (findLast, toReversed, toSorted, with, …)
//
// All seven `interface Array<T> { … }` declarations route to the same
// std:array bucket; mergeDecls concatenates their `Members` slices in
// statement order so that by the time `detectTrios` runs there is
// exactly one `interface Array<T>` (with every method from every lib
// year), one merged `interface ArrayConstructor`, and one `declare var
// Array: ArrayConstructor`. Trio fusion then produces a single
// `class Array<T>` with the union of all members.
//
// The same pattern applies to `Date`, `String`, `Number`, `Math`,
// `Object`, `Promise`, `RegExp`, the typed-array families, `JSON`,
// `Intl`, `Reflect`, `Symbol`, etc. — anywhere TS layers spec
// revisions across multiple lib files, mergeDecls collapses them.
//
// Other declaration kinds are not merged — a duplicated `declare var`
// / `declare class` across lib files is a TS-side error that we let
// fall through to the converter as two decls (the trio detector and
// later passes will flag it).
//
// Statement order is preserved by keeping each merged entry at its
// first occurrence's index.
func mergeDecls(stmts []dts_parser.Statement) []dts_parser.Statement {
	out := make([]dts_parser.Statement, 0, len(stmts))
	ifaceIdx := make(map[string]int) // name → index into out
	nsIdx := make(map[string]int)
	for _, stmt := range stmts {
		switch s := stmt.(type) {
		case *dts_parser.InterfaceDecl:
			if i, ok := ifaceIdx[s.Name.Name]; ok {
				existing := out[i].(*dts_parser.InterfaceDecl)
				existing.Members = append(existing.Members, s.Members...)
				// Extends is concatenated without structural dedup. In
				// practice, TS lib augmentation files add members, not
				// extends clauses (only the initial declaration carries
				// the inheritance chain), so duplicates don't arise from
				// the pinned corpus. If that ever changes, dedup here on
				// a printed form of the TypeAnn.
				existing.Extends = append(existing.Extends, s.Extends...)
				continue
			}
			ifaceIdx[s.Name.Name] = len(out)
			out = append(out, s)
		case *dts_parser.NamespaceDecl:
			if i, ok := nsIdx[s.Name.Name]; ok {
				existing := out[i].(*dts_parser.NamespaceDecl)
				existing.Statements = append(existing.Statements, s.Statements...)
				continue
			}
			nsIdx[s.Name.Name] = len(out)
			out = append(out, s)
		default:
			out = append(out, stmt)
		}
	}
	// Recursively merge inside namespaces.
	for _, stmt := range out {
		if ns, ok := stmt.(*dts_parser.NamespaceDecl); ok {
			ns.Statements = mergeDecls(ns.Statements)
		}
	}
	return out
}

// ConvertBucket runs the standalone-module conversion on a single
// routed bucket. The synthetic Module wraps the bucket's statements
// without a source path — every emitted decl carries its `@js("...")`
// derived from the original dts name, independent of where the file
// is written.
//
// Pre-conversion: same-name interfaces and namespaces are already
// concatenated by mergeDecls (PartitionLib). Here we additionally fuse
// `interface ReadonlyFoo` + `interface Foo` pairs into a single class
// `Foo` — readonly-twin members are appended to `Foo`'s member list if
// missing, and the standalone module's emitted class is then post-
// processed so that each method whose name appears on the twin gets a
// non-mutating `self` receiver (twins are positive evidence the method
// does not mutate, the same contract `mergeReadonlyVariant` in
// [internal/checker/prelude.go](../../internal/checker/prelude.go)
// established for the legacy prelude path).
//
// `ReadonlyFoo` itself is dropped from emission, and no alias stands in
// for it. Escalier spells the immutable view `Foo<…>`, so once the
// rewrite below has respelled every reference there is nothing left for
// the readonly name to denote.
//
// After conversion, rewriteReadonlyTwinRefs walks every TypeAnn slot
// in the emitted module and rewrites references to the twin names so
// they match Escalier's mut-modifier model: TS `ReadonlyFoo<…>` becomes
// `Foo<…>` (immutable view), TS `Foo<…>` becomes `mut Foo<…>` (mutable
// view). `T[]` is already desugared to `Array<T>` by convertTypeAnn so
// it flows through the same rewrite; `readonly T[]` is desugared to
// `ReadonlyArray<T>` for the same reason.
func ConvertBucket(stmts []dts_parser.Statement) (*StandaloneModule, error) {
	stmts, twins := fuseReadonlyTwins(stmts)
	return convertFusedBucket(stmts, twins, twins)
}

// convertFusedBucket converts one already-fused bucket. `own` are the
// twins this bucket declares and `all` are every twin in the tree.
//
// The two differ because a twin's declarations and the references to
// them sit in different packages. `Array` and `ReadonlyArray` are both
// declared in std:array, so only that bucket can merge their members
// and flip a receiver. Every other package references the names without
// declaring them: web:dom alone writes 119 of them. Rewriting against
// `own` leaves those spelled the TypeScript way — a bare `Array<T>`
// where Escalier means `mut Array<T>`, and a `ReadonlyArray<T>` that
// names nothing the tree declares.
func convertFusedBucket(
	stmts []dts_parser.Statement,
	own, all []readonlyTwin,
) (*StandaloneModule, error) {
	mod, err := ConvertToStandaloneModule(&dts_parser.Module{Statements: stmts})
	if err != nil {
		return nil, err
	}
	applyReadonlyTwinReceivers(mod, own)
	rewriteReadonlyTwinRefs(mod, all)
	return mod, nil
}

// readonlyTwin records one (Foo, ReadonlyFoo) pair detected at bucket
// scope. `nonMutatingNames` is the set of member names that appear on
// ReadonlyFoo — presence on the readonly twin is positive evidence the
// member does not mutate, so post-processing flips those members'
// receivers from `mut self` to `self` on the emitted class. Members on
// Foo whose names are absent from this set are left as `mut self`.
type readonlyTwin struct {
	mutableName      string
	readonlyName     string
	nonMutatingNames set.Set[string]
}

// fuseReadonlyTwins detects every (Foo, ReadonlyFoo) interface pair in
// the bucket. For each pair:
//
//   - Members of ReadonlyFoo that do not appear by name on Foo are
//     appended to Foo's member list (so trio fusion picks them up on
//     the emitted class).
//   - The ReadonlyFoo InterfaceDecl is removed from the returned
//     statement slice. A synthesised `type ReadonlyFoo<…> = Foo<…>`
//     alias is emitted later by appendReadonlyAliases so the readonly
//     name still resolves in user code.
//
// Returns the adjusted statements and the per-class twin records the
// post-processor needs.
//
// Mutates input: the mutable InterfaceDecl pointers in `stmts` have
// their `Members` slices extended in place. Callers must not reuse
// `stmts` (or the InterfaceDecl pointers within it) after this call
// expecting the original member lists. Today the only caller is
// ConvertBucket, which feeds the result straight into the converter
// and discards it.
func fuseReadonlyTwins(stmts []dts_parser.Statement) ([]dts_parser.Statement, []readonlyTwin) {
	ifaceByName := make(map[string]*dts_parser.InterfaceDecl, len(stmts))
	for _, stmt := range stmts {
		if iface, ok := stmt.(*dts_parser.InterfaceDecl); ok {
			ifaceByName[iface.Name.Name] = iface
		}
	}

	var twins []readonlyTwin
	dropReadonly := set.NewSet[string]()
	// Iterate stmts (not ifaceByName) so detection order is deterministic.
	// Map iteration would randomize the order in which twins are
	// appended, which downstream determines the order ReadonlyFoo
	// members are folded onto Foo (mutates Members) and the order of
	// emitted `type ReadonlyFoo = Foo` aliases in appendReadonlyAliases —
	// both producing diff churn on committed converter output between
	// runs.
	for _, stmt := range stmts {
		iface, ok := stmt.(*dts_parser.InterfaceDecl)
		if !ok {
			continue
		}
		name := iface.Name.Name
		mutableName, found := strings.CutPrefix(name, "Readonly")
		if !found || mutableName == "" {
			continue
		}
		mutable, ok := ifaceByName[mutableName]
		if !ok {
			continue
		}

		// Build the name set of the readonly side, fold any missing
		// members onto the mutable side.
		nonMutatingNames := set.NewSet[string]()
		haveOnMutable := set.NewSet[string]()
		for _, m := range mutable.Members {
			if key := memberKey(m); key != "" {
				haveOnMutable.Add(key)
			}
		}
		for _, m := range iface.Members {
			key := memberKey(m)
			if key == "" {
				continue
			}
			nonMutatingNames.Add(key)
			if !haveOnMutable.Contains(key) {
				mutable.Members = append(mutable.Members, m)
				haveOnMutable.Add(key)
			}
		}

		twins = append(twins, readonlyTwin{
			mutableName:      mutableName,
			readonlyName:     name,
			nonMutatingNames: nonMutatingNames,
		})
		dropReadonly.Add(name)
	}

	if dropReadonly.Len() == 0 {
		return stmts, nil
	}
	out := stmts[:0:len(stmts)]
	for _, stmt := range stmts {
		if iface, ok := stmt.(*dts_parser.InterfaceDecl); ok && dropReadonly.Contains(iface.Name.Name) {
			continue
		}
		out = append(out, stmt)
	}
	return out, twins
}

// memberKey returns the addressable name of an interface member for
// twin-name deduping. Computed keys like `[Symbol.iterator]` are
// stringified to their dotted form ("Symbol.iterator") so symbol-
// keyed methods participate in the Readonly merge (the legacy prelude
// path keyed on `ObjTypeKey` which covered both string and symbol
// names; this string form is the source-level equivalent). Returns ""
// for keyless members (call/construct/index signatures) — those don't
// participate in the Readonly merge and are never appended.
func memberKey(m dts_parser.InterfaceMember) string {
	switch s := m.(type) {
	case *dts_parser.MethodSignature:
		return propertyKeyString(s.Name)
	case *dts_parser.PropertySignature:
		return propertyKeyString(s.Name)
	case *dts_parser.GetterSignature:
		return propertyKeyString(s.Name)
	case *dts_parser.SetterSignature:
		return propertyKeyString(s.Name)
	}
	return ""
}

// propertyKeyString stringifies a PropertyKey for member-name matching.
// Plain idents and string literals return their text; ComputedKey
// expressions are restricted to well-known-symbol member access
// (`[Symbol.iterator]`, `[Symbol.asyncIterator]`, …) and returned in
// dotted form ("Symbol.iterator"). Any other computed-key shape
// panics: every computed key in the pinned TS lib corpus is a
// `Symbol.*` access, so a new shape is a corpus-change canary —
// silently returning "" would drop the member from the readonly-twin
// fold and miscategorise its receiver. If a legitimate non-Symbol
// shape ever shows up, extend this function (and exprDottedName) to
// cover it explicitly.
func propertyKeyString(pk dts_parser.PropertyKey) string {
	switch k := pk.(type) {
	case *dts_parser.Ident:
		return k.Name
	case *dts_parser.StringLiteral:
		return k.Value
	case *dts_parser.ComputedKey:
		dotted := exprDottedName(k.Expr)
		if strings.HasPrefix(dotted, "Symbol.") {
			return dotted
		}
		panic(fmt.Sprintf(
			"propertyKeyString: computed key %T is not a well-known-symbol "+
				"member access (got %q from expr %T); every computed key in "+
				"the pinned TS lib is `[Symbol.*]` — extend "+
				"propertyKeyString/exprDottedName to cover this new shape, "+
				"otherwise the member would be silently dropped from the "+
				"readonly-twin fold",
			pk, dotted, k.Expr))
	}
	return ""
}

// exprDottedName returns the dotted form of a member-access chain
// ("Symbol.iterator", "Foo.Bar.Baz") rooted at an identifier. Returns
// "" for shapes that can't be reduced to a simple chain.
func exprDottedName(e dts_parser.Expr) string {
	switch n := e.(type) {
	case *dts_parser.IdentExpr:
		return n.Name
	case *dts_parser.MemberExpr:
		left := exprDottedName(n.Object)
		if left == "" {
			return ""
		}
		return left + "." + n.Prop.Name
	}
	return ""
}

// applyReadonlyTwinReceivers walks the top-level Decls of every
// namespace in the standalone module and, for any ClassDecl whose
// name matches a twin's mutableName, sets `Receiver.Mut = false` on
// each instance MethodElem whose name appears in the twin's
// nonMutatingNames set. Static members and non-method elems are left
// alone.
//
// Only top-level classes within each namespace are visited — a class
// nested inside another class or further down inside another decl
// won't be inspected. That's fine for the current corpus: every
// readonly twin in the pinned TS lib (ReadonlyArray, ReadonlyMap,
// ReadonlySet, plus their mutable siblings) is declared at the top
// level. If a future twin lands inside a namespace member, this pass
// will need to recurse.
func applyReadonlyTwinReceivers(mod *StandaloneModule, twins []readonlyTwin) {
	if len(twins) == 0 {
		return
	}
	byName := make(map[string]readonlyTwin, len(twins))
	for _, t := range twins {
		byName[t.mutableName] = t
	}
	mod.Module.Namespaces.Scan(func(_ string, ns *ast.Namespace) bool {
		for _, decl := range ns.Decls {
			cd, ok := decl.(*ast.ClassDecl)
			if !ok {
				continue
			}
			twin, ok := byName[cd.Name.Name]
			if !ok {
				continue
			}
			for _, elem := range cd.Body {
				me, ok := elem.(*ast.MethodElem)
				if !ok || me.Static || me.Receiver == nil {
					continue
				}
				name := classElemName(me.Name)
				if name == "" {
					continue
				}
				if twin.nonMutatingNames.Contains(name) {
					me.Receiver.Mut = false
				}
			}
		}
		return true
	})
}

// classElemName extracts the textual name from a class-elem name slot
// for twin-name matching. Plain idents and string literals return
// their text; ComputedKey expressions are restricted to well-known-
// symbol member access (`[Symbol.iterator]`, …) and returned in
// dotted form ("Symbol.iterator"). Any other computed-key shape
// panics — same corpus-change-canary rationale as propertyKeyString:
// every computed key in the pinned TS lib is `Symbol.*`, so a new
// shape would silently dodge the receiver-flip pass and miscategorise
// the method. Extend this function (and astExprDottedName) if a
// legitimate non-Symbol shape ever shows up.
func classElemName(name ast.ObjKey) string {
	switch k := name.(type) {
	case *ast.IdentExpr:
		return k.Name
	case *ast.StrLit:
		return k.Value
	case *ast.ComputedKey:
		dotted := astExprDottedName(k.Expr)
		if strings.HasPrefix(dotted, "Symbol.") {
			return dotted
		}
		panic(fmt.Sprintf(
			"classElemName: computed key %T is not a well-known-symbol "+
				"member access (got %q from expr %T); every computed key in "+
				"the pinned TS lib is `[Symbol.*]` — extend "+
				"classElemName/astExprDottedName to cover this new shape, "+
				"otherwise the method would silently bypass the "+
				"readonly-twin receiver-flip pass",
			name, dotted, k.Expr))
	}
	return ""
}

// astExprDottedName is the ast-side mirror of exprDottedName.
func astExprDottedName(e ast.Expr) string {
	switch n := e.(type) {
	case *ast.IdentExpr:
		return n.Name
	case *ast.MemberExpr:
		left := astExprDottedName(n.Object)
		if left == "" {
			return ""
		}
		return left + "." + n.Prop.Name
	}
	return ""
}

// ConvertBuckets converts every bucket in result, keyed by package URI.
// Callers that need the converted modules for something other than writing
// them — the ECMA-262 join reads them for the members each package declares —
// go through this instead of converting a second time.
func ConvertBuckets(result *PartitionResult) (map[string]*StandaloneModule, error) {
	// Fuse every bucket before converting any of it, so the reference
	// rewrite below knows every twin name the tree declares and not
	// just the ones its own bucket does. See convertFusedBucket.
	uris := make([]string, 0, len(result.Buckets))
	for uri := range result.Buckets {
		uris = append(uris, uri)
	}
	sort.Strings(uris)

	fused := make(map[string][]dts_parser.Statement, len(result.Buckets))
	own := make(map[string][]readonlyTwin, len(result.Buckets))
	var all []readonlyTwin
	for _, uri := range uris {
		stmts, twins := fuseReadonlyTwins(result.Buckets[uri])
		fused[uri] = stmts
		own[uri] = twins
		all = append(all, twins...)
	}

	mods := make(map[string]*StandaloneModule, len(result.Buckets))
	for _, uri := range uris {
		mod, err := convertFusedBucket(fused[uri], own[uri], all)
		if err != nil {
			return nil, &BucketConvertError{pkgError{uri}, err}
		}
		mods[uri] = mod
	}
	return mods, nil
}

// WriteConvertedTree writes each converted module to its package file under
// outDir, creating parent directories as needed. Every file opens with
// GeneratedHeader, which is what tells a reader of the tree that the
// file is a build output rather than a hand-authored package. Returns
// the package URIs written, sorted.
func WriteConvertedTree(mods map[string]*StandaloneModule, outDir string) ([]string, error) {
	uris := make([]string, 0, len(mods))
	for uri := range mods {
		uris = append(uris, uri)
	}
	sort.Strings(uris)

	written := make([]string, 0, len(uris))
	for _, uri := range uris {
		pkg, ok := PackageForURI(uri)
		if !ok {
			return nil, &UnknownPackageError{pkgError{uri}}
		}
		mod := mods[uri]
		dest := filepath.Join(outDir, filepath.FromSlash(pkg.File))
		dir := filepath.Dir(dest)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, &PackageDirError{pkgError{uri}, dir, err}
		}
		f, err := os.Create(dest)
		if err != nil {
			return nil, &FileWriteError{pkgError{uri}, dest, err}
		}
		_, writeErr := io.WriteString(f, GeneratedHeader)
		if writeErr == nil {
			writeErr = WriteStandaloneModule(mod, f)
		}
		closeErr := f.Close()
		if writeErr != nil {
			return nil, &FileWriteError{pkgError{uri}, dest, writeErr}
		}
		if closeErr != nil {
			return nil, &FileWriteError{pkgError{uri}, dest, closeErr}
		}
		written = append(written, uri)
	}
	return written, nil
}

// ScaffoldNodeDir creates outDir/node/ with a README explaining that
// the directory is reserved for future Node.js runtime APIs and ships
// without `.esc` files. Per §6.1/§6.3 the subtree is intentionally
// unpopulated; the README documents *why* it exists so readers don't
// mistake it for an unfinished migration.
func ScaffoldNodeDir(outDir string) error {
	dir := filepath.Join(outDir, "node")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating node dir: %w", err)
	}
	readme := filepath.Join(dir, "README.md")
	if _, err := os.Stat(readme); err == nil {
		return nil
	}
	const body = "# `node:*` pseudo-package scheme\n\n" +
		"Reserved for Node.js runtime APIs. No `.esc` files are populated yet.\n"
	return os.WriteFile(readme, []byte(body), 0o644)
}

// DiscoverLibFiles returns the basenames of every `lib.*.d.ts` file in
// dir that the converter should ingest. The pinned TS install lives in
// node_modules/.pnpm/typescript@<ver>/node_modules/typescript/lib; the
// playground keeps a smaller curated copy under playground/public/types/.
// Both layouts pass any `lib.*.d.ts` basename — there is no upstream
// list to consult, so "everything matching the glob, sorted" is the
// convention.
//
// `lib.*.full.d.ts` aggregator files (lib.es2018.full.d.ts, …) are
// excluded — they are TS-side bundles that triple-slash-include the
// per-year files, contributing zero new declarations of their own.
// Ingesting them would route every Array/Promise member twice.
func DiscoverLibFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("reading lib dir %s: %w", dir, err)
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasPrefix(name, "lib.") || !strings.HasSuffix(name, ".d.ts") {
			continue
		}
		if strings.HasSuffix(name, ".full.d.ts") {
			continue
		}
		out = append(out, name)
	}
	sort.Strings(out)
	return out, nil
}

// ParseLibFiles reads and parses every name in basenames as a dts
// module rooted at dir. Returns one LibInput per file in the same
// order. Per-file parse errors are joined into a single error with
// the offending filenames; the caller decides whether to proceed.
func ParseLibFiles(dir string, basenames []string) ([]LibInput, error) {
	var inputs []LibInput
	var parseErrs []string
	for _, name := range basenames {
		path := filepath.Join(dir, name)
		contents, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", path, err)
		}
		source := &ast.Source{Path: path, Contents: string(contents)}
		p := dts_parser.NewDtsParser(source)
		mod, errs := p.ParseModule()
		if len(errs) > 0 {
			parseErrs = append(parseErrs, fmt.Sprintf("%s: %v", name, errs))
			continue
		}
		inputs = append(inputs, LibInput{SourceFile: name, Module: mod})
	}
	if len(parseErrs) > 0 {
		return inputs, fmt.Errorf("parse errors: %s", strings.Join(parseErrs, "; "))
	}
	return inputs, nil
}

// ReportPartition prints what the routing pass decided to leave out, so
// the operator reads the drops without dumping the full output. Two
// causes, kept apart: names the partition drops on purpose, and whole
// source files it skips.
//
// It reports no per-package count. A count of the statements routed to a
// package is an input-side number that reads as an output-side one, and
// it sits next to a line saying how many packages the run wrote. What
// each package holds is what `git diff` shows, per §6.4, which is also
// the only side that reflects trio fusion and the overlay.
func ReportPartition(result *PartitionResult, w io.Writer) error {
	// The report is assembled in memory and written once. A
	// strings.Builder write cannot fail, so the body stays free of
	// error plumbing and the caller's writer is touched a single time.
	var b strings.Builder

	// Split the drop list by cause. A name the overlay's root drop file
	// holds is worth naming. A whole dropped source file is worth a
	// count instead, since naming its declarations would misread.
	// lib.scripthost.d.ts augments `Date`, so "Date" in a flat name
	// list would suggest std:date lost its class.
	var dropped []string
	seen := set.NewSet[string]()
	sourceCounts := btree.Map[string, int]{}
	for _, d := range result.Drops {
		if DroppedSources.Contains(d.SourceFile) {
			n, _ := sourceCounts.Get(d.SourceFile)
			sourceCounts.Set(d.SourceFile, n+1)
			continue
		}
		if !seen.Contains(d.Name) {
			seen.Add(d.Name)
			dropped = append(dropped, d.Name)
		}
	}
	if len(dropped) > 0 {
		sort.Strings(dropped)
		fmt.Fprintf(&b, "  drops: %d (%s)\n", len(dropped), strings.Join(dropped, ", "))
	}
	sourceCounts.Scan(func(file string, n int) bool {
		fmt.Fprintf(&b, "  dropped source %s: %d decls\n", file, n)
		return true
	})

	_, err := io.WriteString(w, b.String())
	return err
}

// ReportSingletonKeyDrops prints one line per singleton member the
// conversion skipped because the member's key has no plain-name form
// and AllowedSingletonKeyDrops does not cover it. Nothing is written
// when every skip was allow-listed, which is the state over the pinned
// lib set.
//
// The `generate` subcommand calls this after ReportPartition, so a
// member a TypeScript bump adds under a computed key shows up next to
// the top-level drop counts instead of vanishing into the flattener.
func ReportSingletonKeyDrops(mods map[string]*StandaloneModule, w io.Writer) error {
	type entry struct {
		uri    string
		member SingletonMember
	}
	var entries []entry
	for uri, mod := range mods {
		for _, m := range mod.KeyDrops {
			if AllowedSingletonKeyDrops.Contains(m) {
				continue
			}
			entries = append(entries, entry{uri: uri, member: m})
		}
	}
	if len(entries) == 0 {
		return nil
	}
	sort.Slice(entries, func(i, j int) bool {
		a, b := entries[i], entries[j]
		if a.uri != b.uri {
			return a.uri < b.uri
		}
		if a.member.Singleton != b.member.Singleton {
			return a.member.Singleton < b.member.Singleton
		}
		return a.member.Key < b.member.Key
	})

	var b strings.Builder
	fmt.Fprintf(&b, "  singleton members skipped for a non-name key: %d\n", len(entries))
	for _, e := range entries {
		fmt.Fprintf(&b, "    %s %s[%s]\n", e.uri, e.member.Singleton, e.member.Key)
	}
	_, err := io.WriteString(w, b.String())
	return err
}
