package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// checkScript is the §6.6 CI check under test. `go test` runs with this
// package's directory as its working directory, so the path is relative
// to tools/dts_to_esc.
const checkScript = "../../.github/scripts/check-generated-tree.sh"

// checkedTree is the directory the check is pointed at inside each
// scratch repository, standing in for internal/interop/data.
const checkedTree = "data"

// Two generated packages, cut down to what the check reads: a file the
// generator writes whole and git tracks. arrayPkg and bumpedArrayPkg are
// the same package one TypeScript version apart.
const (
	arrayPkg = `// Code generated by dts_to_esc. DO NOT EDIT.

@js("Array")
export declare class Array<T> {
    length: number
}
`
	bumpedArrayPkg = `// Code generated by dts_to_esc. DO NOT EDIT.

@js("Array")
export declare class Array<T> {
    length: number,
    at(self, index: number) -> T | undefined
}
`
	datePkg = `// Code generated by dts_to_esc. DO NOT EDIT.

@js("Date")
export declare class Date {
    getTime(self) -> number
}
`
)

// writeTree writes every entry of files under dir. A key is a
// slash-separated path relative to dir.
func writeTree(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for rel, contents := range files {
		path := filepath.Join(dir, filepath.FromSlash(rel))
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(contents), 0o644))
	}
}

// runGit runs one git command inside dir and fails the test on a
// non-zero exit. The identity and signing flags keep a commit from
// depending on the machine's git configuration.
func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{
		"-c", "user.email=test@escalier.invalid",
		"-c", "user.name=test",
		"-c", "commit.gpgsign=false",
		"-c", "init.defaultBranch=main",
	}, args...)...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "git %s: %s", strings.Join(args, " "), out)
}

// seedRepo builds a git repository holding files as its committed tree,
// standing in for the checkout CI runs the check on.
func seedRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	runGit(t, dir, "init", "-q")
	writeTree(t, filepath.Join(dir, checkedTree), files)
	runGit(t, dir, "add", "--all", "--force", "--", checkedTree)
	runGit(t, dir, "commit", "-q", "-m", "seed the tree")
	return dir
}

// stubGenerator writes a script that replaces the checked tree with the
// packages under src, standing in for a `dts_to_esc generate` run that
// emits exactly those. It returns the script's path. The script runs
// with the scratch repository as its working directory, which is what
// makes the relative path resolve.
func stubGenerator(t *testing.T, src string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "stub-generate.sh")
	script := fmt.Sprintf("#!/bin/sh\nset -e\nrm -rf '%s'\ncp -R '%s' '%s'\n",
		checkedTree, src, checkedTree)
	require.NoError(t, os.WriteFile(path, []byte(script), 0o755))
	return path
}

// runTreeCheck runs the check inside the scratch repository at dir and
// returns its exit status alongside everything it printed.
func runTreeCheck(t *testing.T, dir string, args ...string) (int, string) {
	t.Helper()
	script, err := filepath.Abs(checkScript)
	require.NoError(t, err)
	cmd := exec.Command(script, args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		// A non-zero exit is a result the caller asserts on. Anything
		// else means the script never ran, so report that instead of
		// the -1 an absent ProcessState would produce.
		var exitErr *exec.ExitError
		require.ErrorAs(t, err, &exitErr, "running %s: %s", script, out)
	}
	return cmd.ProcessState.ExitCode(), string(out)
}

// reportedPaths are the files the check's diff names, read off its
// `diff --git a/<path> b/<path>` headers.
func reportedPaths(output string) []string {
	var paths []string
	for _, line := range strings.Split(output, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 4 && fields[0] == "diff" && fields[1] == "--git" {
			paths = append(paths, strings.TrimPrefix(fields[2], "a/"))
		}
	}
	return paths
}

// TestCheckGeneratedTree covers every row of the §6.6 table. Three of
// the four rows have to fail the check, and the newly emitted package is
// the one a plain `git diff --exit-code` gets wrong. That command
// compares tracked files only, so a package the tree does not carry
// stays untracked and the check passes. Staging before the diff is what
// reports it.
func TestCheckGeneratedTree(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		// committed is the tree the scratch repository holds, and
		// emitted is what the run writes over it.
		committed map[string]string
		emitted   map[string]string
		// reported are the paths the failure's diff names. A nil
		// means the check has to pass.
		reported []string
	}{
		{
			name:      "a clean tree passes",
			committed: map[string]string{"std/array.esc": arrayPkg},
			emitted:   map[string]string{"std/array.esc": arrayPkg},
			reported:  nil,
		},
		{
			name:      "a package whose contents changed fails",
			committed: map[string]string{"std/array.esc": arrayPkg},
			emitted:   map[string]string{"std/array.esc": bumpedArrayPkg},
			reported:  []string{"data/std/array.esc"},
		},
		{
			name:      "a package the run newly emits fails",
			committed: map[string]string{"std/array.esc": arrayPkg},
			emitted: map[string]string{
				"std/array.esc": arrayPkg, "std/date.esc": datePkg},
			reported: []string{"data/std/date.esc"},
		},
		{
			name: "a package the run no longer emits fails",
			committed: map[string]string{
				"std/array.esc": arrayPkg, "std/date.esc": datePkg},
			emitted:  map[string]string{"std/array.esc": arrayPkg},
			reported: []string{"data/std/date.esc"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			repo := seedRepo(t, tc.committed)
			emitted := t.TempDir()
			writeTree(t, emitted, tc.emitted)

			status, output := runTreeCheck(t, repo,
				checkedTree, "--", stubGenerator(t, emitted))

			if tc.reported == nil {
				require.Equal(t, 0, status, output)
				require.Equal(t,
					"check-generated-tree: data matches its inputs\n", output)
				return
			}
			require.Equal(t, 1, status, output)
			lines := strings.SplitN(output, "\n", 3)
			require.Equal(t,
				"check-generated-tree: data does not match its inputs.", lines[0])
			require.Equal(t,
				"Re-run the generator and commit what it writes.", lines[1])
			require.Equal(t, tc.reported, reportedPaths(output))
		})
	}
}

// TestCheckGeneratedTree_ReportsAnIgnoredFile covers the hole a plain
// `git add` would leave. Staging honors .gitignore, so an ignore rule
// matching a generated path would keep that file out of the index and
// the check would report a match it never made. The `*.esc` rule here
// stands in for any rule that happens to match one.
func TestCheckGeneratedTree_ReportsAnIgnoredFile(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t, map[string]string{"std/array.esc": arrayPkg})
	writeTree(t, repo, map[string]string{".gitignore": "*.esc\n"})
	runGit(t, repo, "add", "--", ".gitignore")
	runGit(t, repo, "commit", "-q", "-m", "ignore every .esc file")

	emitted := t.TempDir()
	writeTree(t, emitted, map[string]string{
		"std/array.esc": arrayPkg, "std/date.esc": datePkg})

	status, output := runTreeCheck(t, repo,
		checkedTree, "--", stubGenerator(t, emitted))

	require.Equal(t, 1, status, output)
	require.Equal(t, []string{"data/std/date.esc"}, reportedPaths(output))
}

// TestCheckGeneratedTree_RejectsAMissingSeparator pins the argument
// contract. The generator is everything after `--`, so a call without
// one is a usage error rather than a run of whatever followed.
func TestCheckGeneratedTree_RejectsAMissingSeparator(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t, map[string]string{"std/array.esc": arrayPkg})

	status, output := runTreeCheck(t, repo, checkedTree, "true")

	require.Equal(t, 2, status)
	require.Equal(t,
		"usage: check-generated-tree.sh <tree-dir> -- <generator> [args...]\n",
		output)
}
